### ISSUE TITLE
Error: unacceptable license entry for VEGAS/{{sound}}.ogg

### ISSUE THREAD

**Issue by phet-steele** [phetsims/fraction-matcher#102]
Likely from https://github.com/phetsims/vegas/commit/b240f1fedcc9330c65e52559f46fae23bea961bd.

```
fraction-matcher : build : phet
Failure to grunt snapshot-1521563822458/fraction-matcher:
Running "lint-all" task

Running "clean" task

Running "build" task
Building runnable repository (fraction-matcher, brands: phet)
Building brand: phet
Fatal error: Perennial task failed:
Error: Error: Error: Loader plugin did not call the load callback in the build:
audio:
  audio!VEGAS/ding: Error: unacceptable license entry for VEGAS/ding.ogg
  audio!VEGAS/boing: Error: unacceptable license entry for VEGAS/boing.ogg
  audio!VEGAS/cheer: Error: unacceptable license entry for VEGAS/cheer.ogg
Module loading did not complete for: fraction-matcher-main, FRACTION_MATCHER/FractionsScreen, FRACTION_MATCHER/model/FractionMatcherModel, FRACTION_MATCHER/view/FractionMatcherView, FRACTION_MATCHER/view/LevelsContainerNode, FRACTION_MATCHER/view/LevelNode, FRACTION_MATCHER/MixedNumbersScreen
  at /data/share/phet/continuous-testing/snapshot-1521563822458/chipper/js/grunt/requireBuild.js:107:15
  at /data/share/phet/continuous-testing/snapshot-1521563822458/chipper/node_modules/requirejs/bin/r.js:3059:39
  at /data/share/phet/continuous-testing/snapshot-1521563822458/chipper/node_modules/requirejs/bin/r.js:2999:25
  at Function.prim.nextTick (/data/share/phet/continuous-testing/snapshot-1521563822458/chipper/node_modules/requirejs/bin/r.js:28077:9)
  at Object.errback (/data/share/phet/continuous-testing/snapshot-1521563822458/chipper/node_modules/requirejs/bin/r.js:2998:26)
  at Object.callback (/data/share/phet/continuous-testing/snapshot-1521563822458/chipper/node_modules/requirejs/bin/r.js:2984:23)
  at Object.then (/data/share/phet/continuous-testing/snapshot-1521563822458/chipper/node_modules/requirejs/bin/r.js:3038:23)
  at runBuild (/data/share/phet/continuous-testing/snapshot-1521563822458/chipper/node_modules/requirejs/bin/r.js:30291:48)
  at Object.execCb (/data/share/phet/continuous-testing/snapshot-1521563822458/chipper/node_modules/requirejs/bin/r.js:1946:33)
  at Module.check (/data/share/phet/continuous-testing/snapshot-1521563822458/chipper/node_modules/requirejs/bin/r.js:1133:51)
  at Module.<anonymous> (/data/share/phet/continuous-testing/snapshot-1521563822458/chipper/node_modules/requirejs/bin/r.js:1389:34)
  at /data/share/phet/continuous-testing/snapshot-1521563822458/chipper/node_modules/requirejs/bin/r.js:384:23
  at /data/share/phet/continuous-testing/snapshot-1521563822458/chipper/node_modules/requirejs/bin/r.js:1439:21
  at each (/data/share/phet/continuous-testing/snapshot-1521563822458/chipper/node_modules/requirejs/bin/r.js:309:31)
  at Module.emit (/data/share/phet/continuous-testing/snapshot-1521563822458/chipper/node_modules/requirejs/bin/r.js:1438:17)
  at Module.check (/data/share/phet/continuous-testing/snapshot-1521563822458/chipper/node_modules/requirejs/bin/r.js:1188:30)
  at Module.enable (/data/share/phet/continuous-testing/snapshot-1521563822458/chipper/node_modules/requirejs/bin/r.js:1426:22)
  at Module.init (/data/share/phet/continuous-testing/snapshot-1521563822458/chipper/node_modules/requirejs/bin/r.js:1038:26)
  at Module.<anonymous> (/data/share/phet/continuous-testing/snapshot-1521563822458/chipper/node_modules/requirejs/bin/r.js:1264:30)
  at /data/share/phet/continuous-testing/snapshot-1521563822458/chipper/node_modules/requirejs/bin/r.js:384:23
  at /data/share/phet/continuous-testing/snapshot-1521563822458/chipper/node_modules/requirejs/bin/r.js:2697:17
  at Object.execCb (/data/share/phet/continuous-testing/snapshot-1521563822458/chipper/node_modules/requirejs/bin/r.js:1946:33)
  at Module.check (/data/share/phet/continuous-testing/snapshot-1521563822458/chipper/node_modules/requirejs/bin/r.js:1133:51)
  at Module.enable (/data/share/phet/continuous-testing/snapshot-1521563822458/chipper/node_modules/requirejs/bin/r.js:1426:22)
  at Module.init (/data/share/phet/continuous-testing/snapshot-1521563822458/chipper/node_modules/requirejs/bin/r.js:1038:26)
  at /data/share/phet/continuous-testing/snapshot-1521563822458/chipper/node_modules/requirejs/bin/r.js:1710:36
  at _combinedTickCallback (internal/process/next_tick.js:131:7)
  at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by jbphet** [comment]
Should be fixed by https://github.com/phetsims/fraction-matcher/commit/e38c696f2a1447264d18d3768392ac2b18f928c8

**Comment by jbphet** [comment]
The last continuous test, which started at 3/20/2018, 1:17:59pm, shows 100% pass on fraction-matcher after the fix was made.  I'll wait for one more iteration of continuous test and, if that looks good, I'll close.

**Comment by jbphet** [comment]
Two more continuous test cycles have completed with no problems in fraction-matcher.  Closing.
