### ISSUE TITLE
CT: Cannot read property spotProperty

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/fraction-matcher#106]
```
fraction-matcher : fuzz : built : run
Query: fuzz&memoryLimit=1000
Uncaught TypeError: Cannot read property 'spotProperty' of undefined
TypeError: Cannot read property 'spotProperty' of undefined
    at t.value (https://bayes.colorado.edu/continuous-testing/snapshot-1549446669791/fraction-matcher/build/phet/fraction-matcher_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1039:1094592)
    at listener (https://bayes.colorado.edu/continuous-testing/snapshot-1549446669791/fraction-matcher/build/phet/fraction-matcher_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1039:1122709)
    at e.value (https://bayes.colorado.edu/continuous-testing/snapshot-1549446669791/fraction-matcher/build/phet/fraction-matcher_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1039:27560)
    at e.fire (https://bayes.colorado.edu/continuous-testing/snapshot-1549446669791/fraction-matcher/build/phet/fraction-matcher_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1039:466355)
    at Array.a (https://bayes.colorado.edu/continuous-testing/snapshot-1549446669791/fraction-matcher/build/phet/fraction-matcher_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1039:465491)
    at e.value (https://bayes.colorado.edu/continuous-testing/snapshot-1549446669791/fraction-matcher/build/phet/fraction-matcher_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1039:29245)
    at e.value (https://bayes.colorado.edu/continuous-testing/snapshot-1549446669791/fraction-matcher/build/phet/fraction-matcher_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1039:58509)
    at e.value (https://bayes.colorado.edu/continuous-testing/snapshot-1549446669791/fraction-matcher/build/phet/fraction-matcher_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1039:58235)
    at e.value (https://bayes.colorado.edu/continuous-testing/snapshot-1549446669791/fraction-matcher/build/phet/fraction-matcher_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1039:57834)
    at e.value (https://bayes.colorado.edu/continuous-testing/snapshot-1549446669791/fraction-matcher/build/phet/fraction-matcher_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1039:29245)
id: Bayes Chrome
Approximately 2/6/2019, 2:51:09 AM
fraction-matcher : fuzz : require.js : run
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed
Error: Assertion failed
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1549446669791/assert/js/assert.js:22:13)
    at MatchingChallenge.showAnswer (https://bayes.colorado.edu/continuous-testing/snapshot-1549446669791/fractions-common/js/matching/model/MatchingChallenge.js?bust=1549454443509:259:17)
    at listener (https://bayes.colorado.edu/continuous-testing/snapshot-1549446669791/fractions-common/js/matching/view/MatchingChallengeNode.js?bust=1549454443509:217:35)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1549446669791/axon/js/Emitter.js?bust=1549454443509:229:55)
    at PushButtonModel.fire (https://bayes.colorado.edu/continuous-testing/snapshot-1549446669791/sun/js/buttons/PushButtonModel.js?bust=1549454443509:155:25)
    at Array.downPropertyObserver (https://bayes.colorado.edu/continuous-testing/snapshot-1549446669791/sun/js/buttons/PushButtonModel.js?bust=1549454443509:88:16)
    at Emitter.emit3 (https://bayes.colorado.edu/continuous-testing/snapshot-1549446669791/axon/js/Emitter.js?bust=1549454443509:321:54)
    at BooleanProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1549446669791/axon/js/Property.js?bust=1549454443509:239:27)
    at BooleanProperty.setValueAndNotifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1549446669791/axon/js/Property.js?bust=1549454443509:219:12)
    at BooleanProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1549446669791/axon/js/Property.js?bust=1549454443509:152:14)
id: Bayes Chrome
Approximately 2/6/2019, 2:51:09 AM
fraction-matcher : fuzz : require.js : run
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed
Error: Assertion failed
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1549446669791/assert/js/assert.js:22:13)
    at MatchingChallenge.showAnswer (https://bayes.colorado.edu/continuous-testing/snapshot-1549446669791/fractions-common/js/matching/model/MatchingChallenge.js?bust=1549465906719:259:17)
    at listener (https://bayes.colorado.edu/continuous-testing/snapshot-1549446669791/fractions-common/js/matching/view/MatchingChallengeNode.js?bust=1549465906719:217:35)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1549446669791/axon/js/Emitter.js?bust=1549465906719:229:55)
    at PushButtonModel.fire (https://bayes.colorado.edu/continuous-testing/snapshot-1549446669791/sun/js/buttons/PushButtonModel.js?bust=1549465906719:155:25)
    at Array.downPropertyObserver (https://bayes.colorado.edu/continuous-testing/snapshot-1549446669791/sun/js/buttons/PushButtonModel.js?bust=1549465906719:88:16)
    at Emitter.emit3 (https://bayes.colorado.edu/continuous-testing/snapshot-1549446669791/axon/js/Emitter.js?bust=1549465906719:321:54)
    at BooleanProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1549446669791/axon/js/Property.js?bust=1549465906719:239:27)
    at BooleanProperty.setValueAndNotifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1549446669791/axon/js/Property.js?bust=1549465906719:219:12)
    at BooleanProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1549446669791/axon/js/Property.js?bust=1549465906719:152:14)
id: Bayes Chrome
Approximately 2/6/2019, 2:51:09 AM
fraction-matcher : fuzz : require.js-canvas : run
Query: brand=phet&ea&fuzz&rootRenderer=canvas&memoryLimit=1000
Uncaught Error: Assertion failed
Error: Assertion failed
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1549446669791/assert/js/assert.js:22:13)
    at MatchingChallenge.showAnswer (https://bayes.colorado.edu/continuous-testing/snapshot-1549446669791/fractions-common/js/matching/model/MatchingChallenge.js?bust=1549465272162:259:17)
    at listener (https://bayes.colorado.edu/continuous-testing/snapshot-1549446669791/fractions-common/js/matching/view/MatchingChallengeNode.js?bust=1549465272162:217:35)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1549446669791/axon/js/Emitter.js?bust=1549465272162:229:55)
    at PushButtonModel.fire (https://bayes.colorado.edu/continuous-testing/snapshot-1549446669791/sun/js/buttons/PushButtonModel.js?bust=1549465272162:155:25)
    at Array.downPropertyObserver (https://bayes.colorado.edu/continuous-testing/snapshot-1549446669791/sun/js/buttons/PushButtonModel.js?bust=1549465272162:88:16)
    at Emitter.emit3 (https://bayes.colorado.edu/continuous-testing/snapshot-1549446669791/axon/js/Emitter.js?bust=1549465272162:321:54)
    at BooleanProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1549446669791/axon/js/Property.js?bust=1549465272162:239:27)
    at BooleanProperty.setValueAndNotifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1549446669791/axon/js/Property.js?bust=1549465272162:219:12)
    at BooleanProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1549446669791/axon/js/Property.js?bust=1549465272162:152:14)
id: Bayes Chrome
Approximately 2/6/2019, 2:51:09 AM
```

**Comment by jonathanolson** [comment]
Thanks! Looking into it.

**Comment by jonathanolson** [comment]
Has been solved for a bit.
